### ISSUE TITLE
Waterline reports that 'connections' is no longer supported

### ISSUE THREAD

**Issue by highwaycoder** [devinivy/dogwater#61]
When I run my project that uses dogwater, I get the following error logged:

```
Warning: `connections` is no longer supported.  Please use `datastores` instead.
I get what you mean, so I temporarily renamed it for you this time, but here is a stack trace
so you know where this is coming from in the code, and can change it to prevent future warnings:

Error
    at Object.initialize (/home/chbr1/Projects/cuca-service/node_modules/waterline/lib/waterline.js:143:12)
    at internals.initialize (/home/chbr1/Projects/cuca-service/node_modules/dogwater/lib/index.js:118:15)
    at Items.serial (/home/chbr1/Projects/cuca-service/node_modules/hapi/lib/server.js:418:18)
    at iterate (/home/chbr1/Projects/cuca-service/node_modules/items/lib/index.js:36:13)
    at Object.exports.serial (/home/chbr1/Projects/cuca-service/node_modules/items/lib/index.js:39:9)
    at module.exports.internals.Server.internals.Server._invoke (/home/chbr1/Projects/cuca-service/node_modules/hapi/lib/server.js:415:11)
    at Items.parallel (/home/chbr1/Projects/cuca-service/node_modules/hapi/lib/server.js:272:14)
    at done (/home/chbr1/Projects/cuca-service/node_modules/items/lib/index.js:63:25)
    at process.nextTick (/home/chbr1/Projects/cuca-service/node_modules/hoek/lib/index.js:854:22)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

Versions:
dogwater@2.3.0
hapi@16.6.2
waterline@0.13.1

I know waterline is .1 above the recommended version range from dogwater, but I figured if they're following semver then it should be fine (right? RIGHT?)

**Comment by devinivy** [comment]
Yeah, this issue is that dogwater isn't compatible with the latest version of waterline.  When a module is below v1, breaking changes can be made in minor versions.  So they are still following semver correctly 👍I would happily take a PR to support the latest version of waterline.

**Comment by devinivy** [comment]
See #63
